### ISSUE TITLE
not working for me 

### ISSUE THREAD

**Issue by namit-piriya** [nishanthvijayan/CoderCalendar-Extensions#11]
It does not show anything in the live contests section and in the upcoming contests section.
I simply added the extension from the chrome webstore.
![Screenshot from 2019-11-16 03-38-08](https://user-images.githubusercontent.com/34130842/68979070-8d415200-0822-11ea-8f72-c505fa48019e.png)

**Comment by ninilo97** [comment]
Same, even for me both the sections are empty.

**Comment by nishanthvijayan** [comment]
Yeah I missed AWS payments and they've suspended my account temporarily. It'll be back up soon
