### ISSUE TITLE
Leetcode contest is not showing

### ISSUE THREAD

**Issue by Sarwar05** [nishanthvijayan/CoderCalendar-Extensions#14]
Leetcode is selected but no Leetcode contest is showing in the list.

![image](https://user-images.githubusercontent.com/13794595/83323394-42e46780-a280-11ea-9cec-115d12408d45.png)

**Comment by nishanthvijayan** [comment]
Huh. I'll look into this

**Comment by Sarwar05** [comment]
![image](https://user-images.githubusercontent.com/13794595/105384363-4fb53180-5c3c-11eb-86bb-027c8f854d9b.png)
Hence closing this issue.
