### ISSUE TITLE
Don't see any contest on the extension

### ISSUE THREAD

**Issue by pcyaa** [nishanthvijayan/CoderCalendar-Extensions#22]
I don't see any contest dates on the extension even though I have subscribed for all the coding websites. Please tell me how to fix the bug.

**Comment by NirmalSilwal** [comment]
Hi, is there any update on this issue, as I am facing the same issue. I can't see any upcoming contests while subscribing all the contests. What is the problem?

**Comment by nishanthvijayan** [comment]
Oh! Found the issue. It's a AWS settings issue. Fixing it ASAP

**Comment by nishanthvijayan** [comment]
@NirmalSilwal Fixed now. Closing this. Thank you for raising this.

**Comment by NirmalSilwal** [comment]
thanks, it is up now!
