### ISSUE TITLE
Codechef contest not showing in the list

### ISSUE THREAD

**Issue by sachinsinghjagawat** [nishanthvijayan/CoderCalendar-Extensions#27]
I have attached the photos as proof, this issue started coming on 10th February 2021. Kindly look into this issue.

![Screenshot (241)](https://user-images.githubusercontent.com/63307079/107866341-b58c8600-6e95-11eb-8447-2b15109d8196.png)
![Screenshot (240)](https://user-images.githubusercontent.com/63307079/107866342-b7eee000-6e95-11eb-815c-776764e8533a.png)

**Comment by AmitJakharcodemyself** [comment]
still codechef contests are not visible!!!

**Comment by nishanthvijayan** [comment]
Looking into this today.

**Comment by nishanthvijayan** [comment]
Fixed

**Comment by AmitJakharcodemyself** [comment]
Thanks
