### ISSUE TITLE
Google Calendar location points to the wrong page

### ISSUE THREAD

**Issue by VasilyFomin** [nishanthvijayan/CoderCalendar-Extensions#4]
Hi,

There's a small issue with the created GCal event.

The current link is `http://codeforces.com/contest/XXX` but it should be `contests`, not the missing `s`

Thanks

**Comment by nishanthvijayan** [comment]
Fixed in https://github.com/nishanthvijayan/CoderCalendar-API/commit/1fcd01e2569c0560c94ba523cfd4c09a28890b1f
