### ISSUE TITLE
Not showing any results.

### ISSUE THREAD

**Issue by pprathameshmore** [nishanthvijayan/CoderCalendar-Extensions#6]
![Annotation 2019-08-25 192541](https://user-images.githubusercontent.com/17108186/63650975-2b66d400-c76e-11e9-8cb0-4cf35483e772.jpg)

**Comment by ajraj27** [comment]
Yeah. Not showing any results.

**Comment by nishanthvijayan** [comment]
Yeah I must've missed the AWS bills. Should be back up once I do that :D
