### ISSUE TITLE
"uncheck all" feature

### ISSUE THREAD

**Issue by avi6gupta** [nishanthvijayan/CoderCalendar-Extensions#7]
Can you please add a button to uncheck all coding website in settings frame.

Use: So that we can see contest from a particular website by checking it quickly.

**Comment by nishanthvijayan** [comment]
Should be simple enough. I'll take it up when I get a chance

**Comment by dimglyn** [comment]
Hey @nishanthvijayan! Can I try this out?

**Comment by nishanthvijayan** [comment]
@dimGlyn Sure thing. Ask me if you have questions regarding setup. I'm no react pro, so the frontend code may seem a little messy. Feel free to raise any suggestions
